# Sketchybar Lua generation
# Handles all Nix-to-Lua bridging: constants, item loading, config files.
{
  lib,
  pkgs,
  cfg,
  themeCfg,
}: let
  inherit (lib) getExe;
  inherit (themeCfg) palette;

  # ── Helpers ────────────────────────────────────────────────────────────

  # Convert Nix attrs to Lua table syntax
  toLuaTable = attrs: let
    toLuaValue = v:
      if builtins.isString v
      then "\"${v}\""
      else if builtins.isBool v
      then
        (
          if v
          then "true"
          else "false"
        )
      else if builtins.isAttrs v
      then toLuaTable v
      else if builtins.isList v
      then toLuaList v
      else builtins.toString v;
    fields = lib.mapAttrsToList (k: v: "${k} = ${toLuaValue v}") attrs;
  in "{\n${builtins.concatStringsSep ",\n" fields}\n}";

  # Convert Nix list to Lua array syntax
  toLuaList = list: let
    toLuaValue = v:
      if builtins.isString v
      then "\"${v}\""
      else builtins.toString v;
  in "{${builtins.concatStringsSep ", " (map toLuaValue list)}}";

  # ── Color Mapping ──────────────────────────────────────────────────────

  # Maps a semantic palette to the flat structure expected by Lua config.
  # Reusable for both the active palette and all variant palettes.
  mkSketchybarColors = p: {
    default = p.fg.sketchybar;
    black = p.bg_dim.sketchybar;
    white = p.fg.sketchybar;
    red = p.red.sketchybar;
    red_bright = p.red_bright.sketchybar;
    green = p.green.sketchybar;
    blue = p.accent.sketchybar;
    blue_bright = p.blue_bright.sketchybar;
    yellow = p.yellow.sketchybar;
    orange = p.orange.sketchybar;
    magenta = p.violet.sketchybar;
    grey = p.fg_dim.sketchybar;
    transparent = p.transparent.sketchybar;

    bar = {
      bg = builtins.replaceStrings ["0xff"] ["0xf0"] p.bg.sketchybar;
      border = p.border.sketchybar;
    };

    popup = {
      bg = p.bg.sketchybar;
      border = p.border.sketchybar;
    };

    bg1 = p.bg.sketchybar;
    bg2 = p.border.sketchybar;

    accent = p.accent.sketchybar;
    accent_bright = p.accent_dim.sketchybar;

    spotify_green = p.green.sketchybar;
  };

  # Active palette colors
  sketchybarColors = mkSketchybarColors palette;

  # All variant palettes for runtime theme switching
  allThemeVariants = lib.mapAttrs (_: mkSketchybarColors) themeCfg.allVariantPalettes;

  # ── Items Registry ─────────────────────────────────────────────────────

  # Fixed ordering determines bar layout.
  # Left side first, then right side.
  itemRegistry = [
    {
      luaPath = "items.menus";
      enable = cfg.items.menus.enable;
    }
    {
      luaPath = "items.workspaces";
      enable = cfg.items.workspaces.enable;
    }
    {
      luaPath = "items.calendar";
      enable = cfg.items.calendar.enable;
    }
    {
      luaPath = "items.vpn";
      enable = cfg.items.vpn.enable;
    }
    {
      luaPath = "items.widgets.brew";
      enable = cfg.items.widgets.brew.enable;
    }
    {
      luaPath = "items.widgets.volume";
      enable = cfg.items.widgets.volume.enable;
    }
    {
      luaPath = "items.widgets.battery";
      enable = cfg.items.widgets.battery.enable;
    }
    {
      luaPath = "items.widgets.network";
      enable = cfg.items.widgets.network.enable;
    }
    {
      luaPath = "items.widgets.ram";
      enable = cfg.items.widgets.ram.enable;
    }
    {
      luaPath = "items.widgets.cpu";
      enable = cfg.items.widgets.cpu.enable;
    }
    {
      luaPath = "items.theme_picker";
      enable = cfg.items.themePicker.enable;
    }
    {
      luaPath = "items.pomodoro";
      enable = cfg.items.pomodoro.enable;
    }
    {
      luaPath = "items.clipboard";
      enable = cfg.items.clipboard.enable;
    }
    {
      luaPath = "items.media";
      enable = cfg.items.media.enable;
    }
  ];

  enabledItems = builtins.filter (i: i.enable) itemRegistry;

  generatedItemsInit = let
    requireLines = builtins.concatStringsSep "\n"
      (map (i: "require(\"${i.luaPath}\")") enabledItems);
  in ''
    -- Auto-generated by Nix. Do not edit manually.
    ${requireLines}
  '';

  # ── Per-item Configuration ─────────────────────────────────────────────

  # Only generate config for enabled items that have sub-options
  itemsConfig = let
    optionalItem = enable: config:
      if enable
      then config
      else {};
  in
    lib.filterAttrs (_: v: v != {}) {
      media = optionalItem cfg.items.media.enable {
        whitelist = cfg.items.media.whitelist;
      };
      workspaces = optionalItem cfg.items.workspaces.enable {
        bounce_animation = cfg.items.workspaces.bounceAnimation;
        deferred_loading = cfg.items.workspaces.deferredLoading;
      };
      pomodoro = optionalItem cfg.items.pomodoro.enable {
        default_duration = cfg.items.pomodoro.defaultDuration;
      };
      clipboard = optionalItem cfg.items.clipboard.enable {
        poll_interval = cfg.items.clipboard.pollInterval;
        max_entries = cfg.items.clipboard.maxEntries;
      };
    };

  # ── Packages ───────────────────────────────────────────────────────────

  # Base packages always needed
  basePackages = with pkgs; [
    coreutils
    curl
    gh
    gh-notify
    gnugrep
    gnused
  ];

  # Conditional packages based on enabled items
  conditionalPackages = with pkgs;
    lib.optionals cfg.items.workspaces.enable [aerospace]
    ++ lib.optionals cfg.items.widgets.volume.enable [blueutil switchaudio-osx]
    ++ lib.optionals cfg.items.menus.enable [jankyborders];

  allPackages = basePackages ++ conditionalPackages ++ cfg.extraPackages;

  # ── Shell Integration ──────────────────────────────────────────────────

  shellAliases = {
    restart-sketchybar = ''launchctl kickstart -k gui/"$(id -u)"/org.nix-community.home.sketchybar'';
  };

  brewIntegration = ''
    brew() {
      command brew "$@" && ${getExe cfg.package} --trigger brew_update
    }

    mas() {
      command mas "$@" && ${getExe cfg.package} --trigger brew_update
    }
  '';

  # ── Generated Constants ────────────────────────────────────────────────

  nixConstantsLua = let
    itemsSection =
      if itemsConfig != {}
      then ",\nitems = ${toLuaTable itemsConfig}"
      else "";
  in ''
    -- Auto-generated by Nix. Do not edit manually.
    return {
      colors = ${toLuaTable sketchybarColors},
      themes = ${toLuaTable allThemeVariants},
      active_variant = "${themeCfg.variant}",
      fonts = {
        text = "${cfg.fonts.text}",
        icon = "${cfg.fonts.icon}",
        size = ${toString cfg.fonts.size}
      },
      settings = {
        icons_style = "${cfg.iconsStyle}"
      },
      bar = {
        height = ${toString cfg.bar.height},
        blur_radius = ${toString cfg.bar.blurRadius},
        shadow = ${
      if cfg.bar.shadow
      then "true"
      else "false"
    },
        sticky = ${
      if cfg.bar.sticky
      then "true"
      else "false"
    },
        topmost = "${cfg.bar.topmost}",
        padding_left = ${toString cfg.bar.paddingLeft},
        padding_right = ${toString cfg.bar.paddingRight}
      }${itemsSection}
    }
  '';

  # ── Main Config ────────────────────────────────────────────────────────

  mainConfig = ''
    -- Add config directory to package.path for local modules
    local config_dir = os.getenv("HOME") .. "/.config/sketchybar"
    package.path = package.path .. ";" .. config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua"

    -- Compile C event providers before loading items
    os.execute("(cd " .. config_dir .. "/helpers && make)")

    sbar = require("sketchybar")
    sbar.begin_config()
    require("bar")
    require("default")
    require("items")
    sbar.hotload(true)
    sbar.end_config()
    sbar.event_loop()
  '';

  # ── Config Files ───────────────────────────────────────────────────────

  configFiles = {
    # Copy Lua config files, excluding generated/dead files
    "sketchybar" = {
      source = lib.cleanSourceWith {
        src = ./config;
        filter = name: _type: let
          baseName = baseNameOf name;
        in
          baseName != "sketchybarrc"
          && baseName != "install_dependencies.sh"
          # Exclude all init.lua files — they are now generated by Nix
          && baseName != "init.lua";
      };
      recursive = true;
    };

    # Generated constants — bridges all configurable values to Lua
    "sketchybar/nix_constants.lua".text = nixConstantsLua;

    # Generated items loader — only includes enabled items
    "sketchybar/items/init.lua".text = generatedItemsInit;

    # App icon map from package
    "sketchybar/helpers/icon_map.lua".source = "${pkgs.aytordev.sketchybar-app-font}/lib/sketchybar-app-font/icon_map.lua";
  };
in {
  inherit allPackages shellAliases brewIntegration mainConfig configFiles;
}
