# Runtime theme manager tests.
#
# The constants under test are generated by the real adapter from the real theme
# module, so the catalog covers every registered family/variant rather than a
# hand-written subset. The real helpers/theme.lua runs against those constants
# with a stubbed `sbar`, asserting:
#   - every family/variant is listed and switchable;
#   - invalid and removed persisted themes fall back to the declarative one;
#   - an empty catalog degrades to the active `colors` without erroring;
#   - open/write/close/remove failures return false and never reload.
{pkgs, ...}: let
  inherit (pkgs) lib;

  configDir = ../../modules/home/programs/desktop/bars/sketchybar/config;

  themeCfg =
    (lib.evalModules {
      modules = [
        ../../modules/home/theme
        {
          options.assertions = lib.mkOption {
            type = lib.types.listOf lib.types.attrs;
            default = [];
          };
        }
      ];
    }).config.aytordev.theme;

  adapter = import ../../modules/home/programs/desktop/bars/sketchybar/theme.nix {inherit lib;};
  toLua = import ../../modules/home/programs/desktop/bars/sketchybar/to-lua.nix {inherit lib;};

  inherit (themeCfg) providers;
  activeKey = "${themeCfg.name}/${themeCfg.variant}";
  activeAccent = (adapter.colors {inherit (themeCfg) palette ansi;}).accent;

  allKeys = lib.concatMap (
    family: map (variant: "${family}/${variant}") (builtins.attrNames providers.${family}.variants)
  ) (builtins.attrNames providers);

  constants = adapter.constants {
    theme = themeCfg;
    inherit providers;
  };

  # Constants with one variant removed, to simulate a theme persisted by a
  # previous generation that no longer exists after a Nix change.
  subsetConstants =
    constants
    // {
      themes = builtins.removeAttrs constants.themes ["kanagawa/lotus"];
    };

  # Constants with no catalog at all: the runtime must fall back to `colors`.
  emptyConstants =
    constants
    // {
      themes = {};
    };

  luaConstants = pkgs.writeText "nix_constants.lua" ''
    -- Auto-generated by Nix. Do not edit manually.
    return ${toLua constants}
  '';
  luaSubsetConstants = pkgs.writeText "nix_constants-subset.lua" ''
    -- Auto-generated by Nix. Do not edit manually.
    return ${toLua subsetConstants}
  '';
  luaEmptyConstants = pkgs.writeText "nix_constants-empty.lua" ''
    -- Auto-generated by Nix. Do not edit manually.
    return ${toLua emptyConstants}
  '';

  mkHarness = name: body:
    pkgs.writeText "sketchybar-theme-${name}.lua" ''
      package.path = os.getenv("LUA_WORK") .. "/?.lua;" .. os.getenv("LUA_WORK") .. "/?/init.lua;" .. package.path
      sbar = { execs = {}, exec = function(cmd) table.insert(sbar.execs, cmd) end }
      local function check(cond, msg)
        if not cond then error(msg, 2) end
      end
      local theme = require("helpers.theme")
      local persist = os.getenv("HOME") .. "/.config/sketchybar/.theme_variant"
      ${body}
    '';

  expectedList = "{${lib.concatMapStringsSep ", " toLua allKeys}}";

  catalogHarness = mkHarness "catalog" ''
    theme.init()
    check(theme.active == "${activeKey}", "declarative active_theme")
    check(theme.current == "${activeKey}", "init follows the declarative theme")
    check(theme.palette().accent == ${toLua activeAccent}, "active accent matches")

    local names = theme.list()
    check(#names == ${toString (builtins.length allKeys)}, "list exposes every family/variant")
    for _, key in ipairs(${expectedList}) do
      check(theme.themes[key] ~= nil, "themes is missing " .. key)
    end

    for _, key in ipairs(names) do
      check(theme.apply(key), "apply " .. key .. " returns true")
      check(theme.current == key, "current follows " .. key)
      check(theme.palette().red == theme.themes[key].red, "red matches " .. key)
    end
    check(#sbar.execs == #names, "one reload per successful apply")

    check(theme.apply("no/such-theme") == false, "unknown apply returns false")
    check(#sbar.execs == #names, "unknown apply does not reload")

    check(theme.follow_nix() == true, "follow_nix returns true")
    check(theme.is_following_nix() == true, "follow_nix clears the override")
    check(theme.current == "${activeKey}", "follow_nix restores the declarative theme")
    check(#sbar.execs == #names + 1, "follow_nix reloads exactly once")
  '';

  invalidPersistedHarness = mkHarness "invalid-persisted" ''
    theme.init()
    check(theme.current == "${activeKey}", "invalid persisted falls back")
    check(theme.is_following_nix() == true, "invalid persisted is not an override")
    check(theme.palette().accent == ${toLua activeAccent}, "fallback palette is declarative")
  '';

  removedPersistedHarness = mkHarness "removed-persisted" ''
    theme.init()
    check(theme.themes["kanagawa/lotus"] == nil, "removed theme is absent from the catalog")
    check(theme.current == "${activeKey}", "removed persisted theme falls back")
    check(theme.apply("kanagawa/lotus") == false, "applying a removed theme fails")
    check(#sbar.execs == 0, "no reload for a removed theme")
  '';

  emptyCatalogHarness = mkHarness "empty-catalog" ''
    theme.init()
    check(#theme.list() == 0, "empty catalog lists nothing")
    check(theme.current == nil, "no declarative theme is resolvable")
    check(theme.palette().accent == ${toLua activeAccent}, "palette falls back to constants.colors")
    check(theme.apply("kanagawa/dragon") == false, "apply fails with an empty catalog")
    check(#sbar.execs == 0, "no reload on a failed apply")
    check(theme.follow_nix() == true, "follow_nix succeeds without an override")
    check(#sbar.execs == 1, "follow_nix reloads once")
  '';

  openFailureHarness = mkHarness "open-failure" ''
    local real_open = io.open
    io.open = function(path, mode)
      if path == persist and mode == "w" then
        return nil, "stubbed open failure"
      end
      return real_open(path, mode)
    end
    theme.init()
    local before = theme.current
    check(theme.apply("sora/dark") == false, "open failure returns false")
    check(theme.current == before, "current unchanged on open failure")
    check(#sbar.execs == 0, "no reload on open failure")
  '';

  writeFailureHarness = mkHarness "write-failure" ''
    local real_open = io.open
    io.open = function(path, mode)
      if path == persist and mode == "w" then
        return {
          write = function() return nil, "stubbed write failure" end,
          close = function() return true end,
        }
      end
      return real_open(path, mode)
    end
    theme.init()
    local before = theme.current
    check(theme.apply("sora/dark") == false, "write failure returns false")
    check(theme.current == before, "current unchanged on write failure")
    check(#sbar.execs == 0, "no reload on write failure")
  '';

  closeFailureHarness = mkHarness "close-failure" ''
    local real_open = io.open
    io.open = function(path, mode)
      if path == persist and mode == "w" then
        return {
          write = function() return true end,
          close = function() return nil, "stubbed close failure" end,
        }
      end
      return real_open(path, mode)
    end
    theme.init()
    local before = theme.current
    check(theme.apply("sora/dark") == false, "close failure returns false")
    check(theme.current == before, "current unchanged on close failure")
    check(#sbar.execs == 0, "no reload on close failure")
  '';

  removeFailureHarness = mkHarness "remove-failure" ''
    local real_remove = os.remove
    os.remove = function(path)
      if path == persist then
        return nil, "stubbed remove failure"
      end
      return real_remove(path)
    end
    theme.init()
    check(theme.current == "sora/dark", "seeded persisted theme loads")
    check(theme.follow_nix() == false, "remove failure returns false")
    check(#sbar.execs == 0, "no reload on remove failure")
  '';
in
  pkgs.runCommand "sketchybar-theme-tests"
  {
    nativeBuildInputs = [pkgs.lua];
  }
  ''
    export LUA_WORK="$TMPDIR/work"
    mkdir -p "$LUA_WORK/helpers"
    cp ${configDir}/helpers/theme.lua "$LUA_WORK/helpers/theme.lua"
    cp ${configDir}/helpers/log.lua "$LUA_WORK/helpers/log.lua"

    seed_home() {
      mkdir -p "$TMPDIR/$1/.config/sketchybar"
    }

    use_constants() {
      cat "$1" > "$LUA_WORK/nix_constants.lua"
    }

    # Catalog: every registered family/variant is present and switchable.
    seed_home home-catalog
    use_constants ${luaConstants}
    HOME="$TMPDIR/home-catalog" lua ${catalogHarness}

    # Invalid persisted value.
    seed_home home-invalid
    printf 'not-a-theme\n' > "$TMPDIR/home-invalid/.config/sketchybar/.theme_variant"
    HOME="$TMPDIR/home-invalid" lua ${invalidPersistedHarness}

    # Persisted theme removed from the catalog by a Nix change.
    seed_home home-removed
    use_constants ${luaSubsetConstants}
    printf 'kanagawa/lotus\n' > "$TMPDIR/home-removed/.config/sketchybar/.theme_variant"
    HOME="$TMPDIR/home-removed" lua ${removedPersistedHarness}

    # Empty catalog degrades to the active colors.
    seed_home home-empty
    use_constants ${luaEmptyConstants}
    HOME="$TMPDIR/home-empty" lua ${emptyCatalogHarness}

    # Independent I/O failures must report failure and never reload.
    use_constants ${luaConstants}

    seed_home home-open
    HOME="$TMPDIR/home-open" lua ${openFailureHarness}

    seed_home home-write
    HOME="$TMPDIR/home-write" lua ${writeFailureHarness}

    seed_home home-close
    HOME="$TMPDIR/home-close" lua ${closeFailureHarness}

    seed_home home-remove
    printf 'sora/dark\n' > "$TMPDIR/home-remove/.config/sketchybar/.theme_variant"
    HOME="$TMPDIR/home-remove" lua ${removeFailureHarness}

    touch "$out"
  ''
