# Yazi flavor generator
# Derives a Yazi flavor.toml from the shared semantic palette so Yazi follows
# any registered theme family/variant without vendoring one file per theme.
{palette}: let
  fg = role: palette.${role}.hex;
in ''
  # Generated by Nix from aytordev.theme. Do not edit manually.

  [mgr]
  cwd = { fg = "${fg "accent"}" }
  hovered = { reversed = true }
  preview_hovered = { underline = true }
  find_keyword = { fg = "${fg "yellow_bright"}", bold = true, italic = true, underline = true }
  find_position = { fg = "${fg "violet"}", bg = "reset", bold = true, italic = true }
  marker_copied = { fg = "${fg "green"}", bg = "${fg "green"}" }
  marker_cut = { fg = "${fg "red"}", bg = "${fg "red"}" }
  marker_marked = { fg = "${fg "accent"}", bg = "${fg "accent"}" }
  marker_selected = { fg = "${fg "yellow"}", bg = "${fg "yellow"}" }
  count_copied = { fg = "${fg "bg"}", bg = "${fg "green"}" }
  count_cut = { fg = "${fg "bg"}", bg = "${fg "red"}" }
  count_selected = { fg = "${fg "bg"}", bg = "${fg "yellow"}" }
  border_symbol = "│"
  border_style = { fg = "${fg "fg_dim"}" }

  [tabs]
  active = { fg = "${fg "bg"}", bg = "${fg "accent"}", bold = true }
  inactive = { fg = "${fg "accent"}", bg = "${fg "bg_gutter"}" }

  [mode]
  normal_main = { fg = "${fg "bg"}", bg = "${fg "accent"}", bold = true }
  normal_alt = { fg = "${fg "accent"}", bg = "${fg "bg_gutter"}" }
  select_main = { fg = "${fg "bg"}", bg = "${fg "green"}", bold = true }
  select_alt = { fg = "${fg "green"}", bg = "${fg "bg_gutter"}" }
  unset_main = { fg = "${fg "bg"}", bg = "${fg "violet"}", bold = true }
  unset_alt = { fg = "${fg "violet"}", bg = "${fg "bg_gutter"}" }

  [status]
  perm_sep = { fg = "${fg "fg_dim"}" }
  perm_type = { fg = "${fg "accent"}" }
  perm_read = { fg = "${fg "yellow"}" }
  perm_write = { fg = "${fg "red"}" }
  perm_exec = { fg = "${fg "green"}" }
  progress_label = { fg = "${fg "fg"}", bold = true }
  progress_normal = { fg = "${fg "green"}", bg = "${fg "bg_gutter"}" }
  progress_error = { fg = "${fg "yellow"}", bg = "${fg "red"}" }

  [pick]
  border = { fg = "${fg "accent"}" }
  active = { fg = "${fg "violet"}", bold = true }
  inactive = {}

  [input]
  border = { fg = "${fg "accent"}" }
  title = {}
  value = {}
  selected = { reversed = true }

  [cmp]
  border = { fg = "${fg "accent"}" }

  [tasks]
  border = { fg = "${fg "accent"}" }
  title = {}
  hovered = { fg = "${fg "violet"}", bold = true }

  [which]
  mask = { bg = "${fg "bg_gutter"}" }
  cand = { fg = "${fg "accent"}" }
  rest = { fg = "${fg "fg_dim"}" }
  desc = { fg = "${fg "violet"}" }
  separator = "  "
  separator_style = { fg = "${fg "overlay"}" }

  [help]
  on = { fg = "${fg "accent"}" }
  run = { fg = "${fg "violet"}" }
  hovered = { reversed = true, bold = true }
  footer = { fg = "${fg "bg_gutter"}", bg = "${fg "fg"}" }

  [spot]
  border = { fg = "${fg "accent"}" }
  title = { fg = "${fg "accent"}" }
  tbl_col = { fg = "${fg "accent"}" }
  tbl_cell = { fg = "${fg "violet"}", bg = "${fg "bg_gutter"}" }

  [notify]
  title_info = { fg = "${fg "green"}" }
  title_warn = { fg = "${fg "yellow"}" }
  title_error = { fg = "${fg "red"}" }

  [filetype]
  rules = [
    { mime = "image/*", fg = "${fg "accent"}" },
    { mime = "{audio,video}/*", fg = "${fg "yellow"}" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "${fg "violet"}" },
    { mime = "application/{pdf,doc,rtf}", fg = "${fg "green"}" },
    { mime = "vfs/{absent,stale}", fg = "${fg "fg_dim"}" },
    { url = "*", fg = "${fg "fg"}" },
    { url = "*/", fg = "${fg "accent"}" },
    { name = "*", fg = "${fg "fg"}" },
    { name = "*/", fg = "${fg "accent"}" },
  ]
''
