{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  coreAliases = {
    g = "git";
    add = "git add";
    commit = "git commit";
    pull = "git pull";
    push = "git push";
    st = "git status -sb";
    d = "git diff";
    gdiff = "git diff HEAD";
    vdiff = "git difftool HEAD";
  };
in {
  # Combine all aliases into a single attribute set
  allAliases = lib.foldl' (acc: x: acc // x) {} [
    coreAliases
  ];

  # Generate the content for the git aliases file
  generateGitAliasesFile = aliases: ''
    # Git aliases for Bash
    # This file is automatically generated by the git module
    # Do not edit this file directly as it will be overwritten

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: value: "alias ${name}='${value}'") aliases)}
  '';
}
