name: Check
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    name: Check ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64-linux
          - os: macos-latest
            arch: aarch64-darwin
    steps:
      - uses: actions/checkout@v7
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v14
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            system = ${{ matrix.arch }}
            extra-platforms = ${{ matrix.arch }}
      - uses: cachix/cachix-action@v17
        with:
          name: anyrun
          extraPullNames: nix-community
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: run flake check
        run: nix flake check --override-input secrets path:./checks/fixtures/secrets --accept-flake-config
